[project]
name = "pythottler"
version = "0.1.0"
description = "Add a short description here"
authors = ["raceychan <raceychan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.10"
setuptools = ">=69.2.0,<69.3"

[pypi-dependencies]
redis = ">=5.0.3"

[environments]
test = ["test"]

[feature.test.dependencies]
pytest = ">=7.3"
pytest-cov = ">=3.0"
pytest-asyncio = "*"
