[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
# addopts = "--strict-markers --maxfail=1 --pdbcls=IPython.terminal.debugger:Pdb"
addopts = "--strict-markers --maxfail=1"
markers = [
    "integration_test: marks tests as slow integration tests (deselect with '-m \"not integration_test\"')",
]

filterwarnings = ["ignore::DeprecationWarning"]
