name: docs
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material[imaging]
      - run: pip install mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force